/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as GiftCardsRouteImport } from './routes/gift-cards'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as BookingConfirmedRouteImport } from './routes/booking-confirmed'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff/index'
import { Route as AuthenticatedStaffAppointmentsRouteImport } from './routes/_authenticated/staff/appointments'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCardsRoute = GiftCardsRouteImport.update({
  id: '/gift-cards',
  path: '/gift-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmedRoute = BookingConfirmedRouteImport.update({
  id: '/booking-confirmed',
  path: '/booking-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedStaffAppointmentsRoute =
  AuthenticatedStaffAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRouteWithChildren
  '/book': typeof BookRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/gallery': typeof GalleryRoute
  '/gift-cards': typeof GiftCardsRoute
  '/service': typeof ServiceRoute
  '/services': typeof ServicesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/staff/appointments': typeof AuthenticatedStaffAppointmentsRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRouteWithChildren
  '/book': typeof BookRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/gallery': typeof GalleryRoute
  '/gift-cards': typeof GiftCardsRoute
  '/service': typeof ServiceRoute
  '/services': typeof ServicesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/staff/appointments': typeof AuthenticatedStaffAppointmentsRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRouteWithChildren
  '/book': typeof BookRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/gallery': typeof GalleryRoute
  '/gift-cards': typeof GiftCardsRoute
  '/service': typeof ServiceRoute
  '/services': typeof ServicesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/staff/appointments': typeof AuthenticatedStaffAppointmentsRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/auth'
    | '/book'
    | '/booking-confirmed'
    | '/gallery'
    | '/gift-cards'
    | '/service'
    | '/services'
    | '/admin'
    | '/staff'
    | '/auth/callback'
    | '/staff/appointments'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/auth'
    | '/book'
    | '/booking-confirmed'
    | '/gallery'
    | '/gift-cards'
    | '/service'
    | '/services'
    | '/admin'
    | '/auth/callback'
    | '/staff/appointments'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/appointments'
    | '/auth'
    | '/book'
    | '/booking-confirmed'
    | '/gallery'
    | '/gift-cards'
    | '/service'
    | '/services'
    | '/_authenticated/admin'
    | '/_authenticated/staff'
    | '/auth/callback'
    | '/_authenticated/staff/appointments'
    | '/_authenticated/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppointmentsRoute: typeof AppointmentsRoute
  AuthRoute: typeof AuthRouteWithChildren
  BookRoute: typeof BookRoute
  BookingConfirmedRoute: typeof BookingConfirmedRoute
  GalleryRoute: typeof GalleryRoute
  GiftCardsRoute: typeof GiftCardsRoute
  ServiceRoute: typeof ServiceRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-cards': {
      id: '/gift-cards'
      path: '/gift-cards'
      fullPath: '/gift-cards'
      preLoaderRoute: typeof GiftCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmed': {
      id: '/booking-confirmed'
      path: '/booking-confirmed'
      fullPath: '/booking-confirmed'
      preLoaderRoute: typeof BookingConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/appointments': {
      id: '/_authenticated/staff/appointments'
      path: '/appointments'
      fullPath: '/staff/appointments'
      preLoaderRoute: typeof AuthenticatedStaffAppointmentsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
  }
}

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffAppointmentsRoute: typeof AuthenticatedStaffAppointmentsRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffAppointmentsRoute: AuthenticatedStaffAppointmentsRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppointmentsRoute: AppointmentsRoute,
  AuthRoute: AuthRouteWithChildren,
  BookRoute: BookRoute,
  BookingConfirmedRoute: BookingConfirmedRoute,
  GalleryRoute: GalleryRoute,
  GiftCardsRoute: GiftCardsRoute,
  ServiceRoute: ServiceRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
